version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-angular
    ports:
      - "4200:80"
    depends_on:
      - middleware
    networks:
      - app-network

  backend:
    build:
      context: ./backend-springboot
    ports:
      - "8080:8080"
    networks:
      - app-network

  middleware:
    build:
      context: ./gateway-node
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
